[package]
name = "midi_file"
version = "0.1.1"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"
exclude = [
    ".github",
    ".gitignore",
    ".idea",
    ".run",
    "examples/",
    "tests/",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "For reading and writing MIDI files."
repository = "https://github.com/webern/midi_file"
keywords = ["MIDI"]
categories = ["encoding"]

[dependencies]
# this library does not use dependencies

[dev-dependencies]
tempfile = "3"
